[project]
name = "furrrow-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jianyu.an", email = "jianyu234@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "bibtexparser<2",
    "pyyaml>=6.0.3",
    "scholarly>=1.7.11",
]

[project.scripts]
furrrow-github-io = "furrrow_github_io:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
